application:
  name: customer-ms

server:
  port: 9091

spring:
  data:
    mongodb:
      database: mongodbms
      host: localhost
      port: 27017
      
customer:
  types: PERSONAL, EMPRESARIAL
  type:
    personal: PERSONAL
    empresarial: EMPRESARIAL
    
    
#Actuator      
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true