application:
  name: product-ms

server:
  port: 9092

spring:
  data:
    mongodb:
      database: mongodbms
      host: mongodb
      port: 27017
      
customer:
  product: 
    type:
      id: 1,2,3,4,5,6
  type:
    personal: PERSONAL
    empresarial: EMPRESARIAL
  ms:
    uri: http://customer-ms:9091/customer
    
#Actuator      
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-ms:8761/eureka